"""
InDesign Cover Generator for Astrology Birth Charts

This module provides functionality to generate InDesign covers for astrology birth chart reports.
It creates both black and blue cover variants and exports them as PDFs.
"""

import os
import tempfile
import subprocess
import platform
from datetime import datetime
from pathlib import Path

# ===== MANUAL CONFIGURATION =====
# If automatic detection fails, set your InDesign path here:
# For macOS, use the full path to the .app file, e.g., "/Applications/Adobe InDesign 2022/Adobe InDesign 2022.app"
# For Windows, use the full path to InDesign.exe, e.g., "C:\Program Files\Adobe\Adobe InDesign 2022\InDesign.exe"
MANUAL_INDESIGN_PATH = "/Applications/Adobe InDesign 2020/Adobe InDesign 2020.app"  # Set to the detected InDesign path


def generate_indesign_covers(name, birth_info, location):
    """
    Generate InDesign covers for a birth chart report.
    
    Args:
        name (str): Person's name
        birth_info (str): Birth date and time formatted as "May 10, 2005 - 6:04 AM"
        location (str): Birth location formatted as "City, State, Country"
        
    Returns:
        dict: Result with success status, output folder path, and any error message
    """
    try:
        print(f"Starting cover generation for {name}")
        print(f"Birth info: {birth_info}")
        print(f"Location: {location}")
        
        # Create output folder on desktop with user's name
        desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
        folder_name = f"{name.replace(' ', '_')}_Covers"
        output_folder = os.path.join(desktop_path, folder_name)
        print(f"Output folder will be: {output_folder}")
        
        # Create the folder if it doesn't exist
        os.makedirs(output_folder, exist_ok=True)
        print(f"Output folder created or already exists")
        
        # Create temporary ExtendScript file
        print("Creating JSX script...")
        jsx_script = _create_jsx_script(name, birth_info, location, output_folder)
        print(f"JSX script created at: {jsx_script}")
        
        # Run the script with InDesign
        print("Running InDesign script...")
        _run_indesign_script(jsx_script)
        print("InDesign script execution completed")
        
        # Check if PDFs were created
        black_pdf = os.path.join(output_folder, f"{name}_Black_Cover.pdf")
        blue_pdf = os.path.join(output_folder, f"{name}_Blue_Cover.pdf")
        
        if os.path.exists(black_pdf) and os.path.exists(blue_pdf):
            print(f"PDF files successfully created in {output_folder}")
            return {
                'success': True,
                'output_folder': output_folder,
                'error': None
            }
        else:
            print(f"PDF files not found in {output_folder}")
            missing = []
            if not os.path.exists(black_pdf):
                missing.append(f"{name}_Black_Cover.pdf")
            if not os.path.exists(blue_pdf):
                missing.append(f"{name}_Blue_Cover.pdf")
            return {
                'success': False,
                'output_folder': output_folder,
                'error': f"PDF files not created. Missing: {', '.join(missing)}"
            }
    
    except Exception as e:
        import traceback
        print(f"Error in generate_indesign_covers: {e}")
        print(traceback.format_exc())
        return {
            'success': False,
            'output_folder': None,
            'error': str(e)
        }


def _create_jsx_script(name, birth_info, location, output_folder):
    """
    Create an ExtendScript (.jsx) file for InDesign to execute.
    
    Args:
        name (str): Person's name
        birth_info (str): Birth date and time
        location (str): Birth location
        output_folder (str): Path to output folder
    
    Returns:
        str: Path to the created JSX file
    """
    # Template path - Using the template in the INDESIGN FILES folder
    template_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "INDESIGN FILES", "Cover - AstroBookGenerator.indt")
    
    # Convert backslashes to forward slashes for InDesign (works on both platforms)
    safe_template_path = template_path.replace('\\', '/')
    safe_output_folder = output_folder.replace('\\', '/')
    
    # Create the JSX script content - using string concatenation to avoid f-string issues
    script_content = (
        "// InDesign script to generate astrology chart covers\n"
        "// Generated by AstroBookGenerator\n\n"
        "// Error handling wrapper\n"
        "function main() {\n"
        "    if (app.documents.length > 0) {\n"
        "        if (!confirm(\"This script will close all open documents. Continue?\")) {\n"
        "            return;\n"
        "        }\n"
        "        closeAllDocs();\n"
        "    }\n\n"
        "    try {\n"
        "        // Define paths\n"
        "        var templatePath = \"" + safe_template_path + "\";\n"
        "        var outputFolder = \"" + safe_output_folder + "\";\n\n"
        "        // User data to populate\n"
        "        var userData = {\n"
        "            name: \"" + name + "\",\n"
        "            birthInfo: \"" + birth_info + "\",\n"
        "            location: \"" + location + "\"\n"
        "        };\n"
    )
    
    # Continue building the script with string concatenation
    script_content += (
        "        // Check if template exists\n"
        "        var templateFile = new File(templatePath);\n"
        "        if (!templateFile.exists) {\n"
        "            alert(\"Template file not found at: \" + templatePath + \"\\n\\nPlease update the template path in the script.\");\n"
        "            return false;\n"
        "        }\n\n"
        "        // Open the template\n"
        "        var doc = app.open(templateFile);\n\n"
        "        // Replace placeholder text\n"
        "        replaceText(doc, \"{{NAME}}\", userData.name);\n"
        "        replaceText(doc, \"{{BIRTH_INFO}}\", userData.birthInfo);\n"
        "        replaceText(doc, \"{{LOCATION}}\", userData.location);\n\n"
        "        // Export black cover (page 1)\n"
        "        exportPDF(doc, outputFolder, userData.name + \"_Black_Cover\", 1);\n\n"
        "        // Export blue cover (page 2)\n"
        "        exportPDF(doc, outputFolder, userData.name + \"_Blue_Cover\", 2);\n\n"
        "        // Close without saving\n"
        "        doc.close(SaveOptions.NO);\n\n"
        "        return true;\n"
        "    } catch (e) {\n"
        "        alert(\"Error: \" + e);\n"
        "        return false;\n"
        "    }\n"
        "}\n\n"
        "// Function to replace text in the document\n"
        "function replaceText(doc, findText, replaceText) {\n"
        "    app.findTextPreferences = NothingEnum.nothing;\n"
        "    app.changeTextPreferences = NothingEnum.nothing;\n\n"
        "    app.findTextPreferences.findWhat = findText;\n"
        "    app.changeTextPreferences.changeTo = replaceText;\n\n"
        "    doc.changeText();\n\n"
        "    app.findTextPreferences = NothingEnum.nothing;\n"
        "    app.changeTextPreferences = NothingEnum.nothing;\n"
        "}\n\n"
        "// Function to export a specific page as PDF\n"
        "function exportPDF(doc, outputFolder, filename, pageNumber) {\n"
        "    var exportPreset = \"[High Quality Print]\";\n\n"
        "    // Create PDF export preferences\n"
        "    var pdfExportPrefs = app.pdfExportPreferences;\n\n"
        "    // Store original settings\n"
        "    var originalPageRange = pdfExportPrefs.pageRange;\n\n"
        "    // Set to export only the specified page\n"
        "    pdfExportPrefs.pageRange = pageNumber.toString();\n\n"
        "    // Set output path\n"
        "    var outputFile = new File(outputFolder + \"/\" + filename + \".pdf\");\n\n"
        "    // Export the PDF\n"
        "    doc.exportFile(ExportFormat.pdfType, outputFile, false, exportPreset);\n\n"
        "    // Restore original settings\n"
        "    pdfExportPrefs.pageRange = originalPageRange;\n"
        "}\n\n"
        "// Function to close all open documents\n"
        "function closeAllDocs() {\n"
        "    while (app.documents.length > 0) {\n"
        "        app.documents[0].close(SaveOptions.NO);\n"
        "    }\n"
        "}\n\n"
        "// Run the main function\n"
        "main();\n"
    )
    
    # Create a temporary file for the script
    fd, script_path = tempfile.mkstemp(suffix='.jsx')
    os.close(fd)
    
    # Write the script to the file
    with open(script_path, 'w') as f:
        f.write(script_content)
    
    return script_path


def _run_indesign_script(script_path):
    """
    Run an ExtendScript file with Adobe InDesign.
    
    Args:
        script_path (str): Path to the JSX script file
    """
    system = platform.system()
    print(f"Operating system: {system}")
    
    try:
        # Check if manual path is provided
        if MANUAL_INDESIGN_PATH and os.path.exists(MANUAL_INDESIGN_PATH):
            indesign_path = MANUAL_INDESIGN_PATH
            print(f"Using manual InDesign path: {indesign_path}")
            
            if system == "Darwin":  # macOS
                # Run the script with osascript
                cmd = [
                    "osascript", "-e", 
                    f'tell application "{indesign_path}" to do script "{script_path}" language javascript'
                ]
                print(f"Executing command: {' '.join(cmd)}")
                result = subprocess.run(cmd, check=True, capture_output=True, text=True)
                print(f"Command output: {result.stdout}")
                if result.stderr:
                    print(f"Command error: {result.stderr}")
            elif system == "Windows":  # Windows
                # Run the script with InDesign
                cmd = [indesign_path, "-script", script_path]
                print(f"Executing command: {' '.join(cmd)}")
                result = subprocess.run(cmd, check=True, capture_output=True, text=True)
                print(f"Command output: {result.stdout}")
                if result.stderr:
                    print(f"Command error: {result.stderr}")
            else:
                raise Exception(f"Unsupported operating system: {system}")
                
            return
        
        # If no manual path or it doesn't exist, try automatic detection
        if system == "Darwin":  # macOS
            # Try to find InDesign application - more comprehensive search
            indesign_paths = [
                # Standard paths
                "/Applications/Adobe InDesign 2023/Adobe InDesign 2023.app",
                "/Applications/Adobe InDesign 2022/Adobe InDesign 2022.app",
                "/Applications/Adobe InDesign 2021/Adobe InDesign 2021.app",
                "/Applications/Adobe InDesign 2020/Adobe InDesign 2020.app",
                "/Applications/Adobe InDesign CC 2020/Adobe InDesign CC 2020.app",
                "/Applications/Adobe InDesign CC 2019/Adobe InDesign CC 2019.app",
                "/Applications/Adobe InDesign CC 2018/Adobe InDesign CC 2018.app",
                "/Applications/Adobe InDesign CC 2017/Adobe InDesign CC 2017.app",
                "/Applications/Adobe InDesign CC 2015/Adobe InDesign CC 2015.app",
                # Alternative paths
                "/Applications/Adobe InDesign/Adobe InDesign.app",
                "/Applications/Adobe InDesign.app",
                # Search in Applications folder for any InDesign app
            ]
            
            indesign_path = None
            for path in indesign_paths:
                if os.path.exists(path):
                    indesign_path = path
                    break
            
            # If not found in predefined paths, try to find any InDesign app in Applications
            if indesign_path is None:
                # Look for any folder or app with 'InDesign' in the name
                applications_dir = "/Applications"
                for item in os.listdir(applications_dir):
                    if "indesign" in item.lower():
                        potential_path = os.path.join(applications_dir, item)
                        # If it's a directory, look for .app inside
                        if os.path.isdir(potential_path):
                            for subitem in os.listdir(potential_path):
                                if subitem.lower().endswith(".app") and "indesign" in subitem.lower():
                                    indesign_path = os.path.join(potential_path, subitem)
                                    break
                        # If it's an app directly
                        elif item.lower().endswith(".app"):
                            indesign_path = potential_path
                        
                        if indesign_path:
                            break
            
            if indesign_path is None:
                # Try a different approach - use the 'mdfind' command to locate InDesign
                try:
                    result = subprocess.run(["mdfind", "kMDItemCFBundleIdentifier == 'com.adobe.InDesign'"], 
                                           capture_output=True, text=True, check=False)
                    paths = result.stdout.strip().split('\n')
                    if paths and paths[0]:
                        indesign_path = paths[0]
                except:
                    pass
                    
            if indesign_path is None:
                raise Exception("Adobe InDesign not found. Please install InDesign or update the script with the correct path.\n\n"
                               "If InDesign is installed, you can manually specify the path by editing the indesign_generator.py file.")
            
            # Run the script with osascript
            try:
                # First try with full path
                cmd = [
                    "osascript", "-e", 
                    f'tell application "{indesign_path}" to do script "{script_path}" language javascript'
                ]
                subprocess.run(cmd, check=True)
            except subprocess.CalledProcessError:
                # If that fails, try with just the application name
                app_name = os.path.basename(indesign_path)
                if app_name.endswith(".app"):
                    app_name = app_name[:-4]  # Remove .app extension
                
                cmd = [
                    "osascript", "-e", 
                    f'tell application "{app_name}" to do script "{script_path}" language javascript'
                ]
                subprocess.run(cmd, check=True)
            
        elif system == "Windows":  # Windows
            # Try to find InDesign executable
            program_files = os.environ.get("ProgramFiles", "C:\\Program Files")
            indesign_paths = [
                os.path.join(program_files, "Adobe", "Adobe InDesign 2023", "InDesign.exe"),
                os.path.join(program_files, "Adobe", "Adobe InDesign 2022", "InDesign.exe"),
                os.path.join(program_files, "Adobe", "Adobe InDesign 2021", "InDesign.exe"),
                os.path.join(program_files, "Adobe", "Adobe InDesign 2020", "InDesign.exe"),
                os.path.join(program_files, "Adobe", "Adobe InDesign CC 2019", "InDesign.exe"),
                os.path.join(program_files, "Adobe", "Adobe InDesign CC 2018", "InDesign.exe"),
            ]
            
            indesign_path = None
            for path in indesign_paths:
                if os.path.exists(path):
                    indesign_path = path
                    break
            
            # If not found in standard paths, try to search in Program Files
            if indesign_path is None:
                # Look for any folder with 'InDesign' in the name
                for root, dirs, files in os.walk(program_files):
                    for dir_name in dirs:
                        if "indesign" in dir_name.lower():
                            # Look for InDesign.exe
                            potential_path = os.path.join(root, dir_name, "InDesign.exe")
                            if os.path.exists(potential_path):
                                indesign_path = potential_path
                                break
                    if indesign_path:
                        break
            
            # Also check Program Files (x86) if available
            if indesign_path is None and "ProgramFiles(x86)" in os.environ:
                program_files_x86 = os.environ["ProgramFiles(x86)"]
                for root, dirs, files in os.walk(program_files_x86):
                    for dir_name in dirs:
                        if "indesign" in dir_name.lower():
                            # Look for InDesign.exe
                            potential_path = os.path.join(root, dir_name, "InDesign.exe")
                            if os.path.exists(potential_path):
                                indesign_path = potential_path
                                break
                    if indesign_path:
                        break
            
            if indesign_path is None:
                raise Exception("Adobe InDesign not found. Please install InDesign or update the script with the correct path.\n\n"
                               "If InDesign is installed, you can manually specify the path by editing the indesign_generator.py file.")
            
            # Run the script with InDesign
            cmd = [indesign_path, "-script", script_path]
            subprocess.run(cmd, check=True)
            
        else:
            raise Exception(f"Unsupported operating system: {system}")
        
    finally:
        # Clean up the temporary script file
        try:
            os.remove(script_path)
        except:
            pass


if __name__ == "__main__":
    # Test the script
    result = generate_indesign_covers(
        name="Test User",
        birth_info="January 1, 2000 - 12:00 PM",
        location="New York, NY, USA"
    )
    
    print("Success:", result['success'])
    if result['success']:
        print("Output folder:", result['output_folder'])
    else:
        print("Error:", result['error'])
